name = "krisjenk"
account_id = "16a04bbc76ee5eccbcc1d6c39bc9a797"

main = "./build/index.js"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2022-04-05"
compatibility_flags = ["streams_enable_constructors"]

workers_dev = true
logpush = true
node_compat = true

usage_model = 'bundled'

routes = [
    "krisjenkinson.com",
    "www.krisjenkinson.com",
]

[site]
  bucket = "./public"

[build]
  command = "npm run build"
